/**
 * A database laid out over several containers: a MongoDB replica set, a MongoDB
 * sharded cluster, a MySQL primary with read replicas. Which containers there
 * are and what they are called, the command each one starts with, and the steps
 * that join them once they answer.
 *
 * Pure, like `database-maintenance`: everything here returns names and argument
 * vectors and runs nothing, so the exact commands a layout produces are read in
 * a test. Every host that reaches a script is a container name checked against
 * `CONTAINER_NAME`, and every string that reaches JavaScript or SQL is written
 * as a JSON or SQL literal, never spliced in raw.
 *
 * The MongoDB commands follow the manual's own procedures - "Deploy a
 * Self-Managed Replica Set With Keyfile Authentication" and "Deploy a
 * Self-Managed Sharded Cluster with Keyfile Authentication" - and the MySQL
 * ones "Setting Up Replication Using GTIDs" and `CHANGE REPLICATION SOURCE TO`
 * in the 8.4 manual.
 */

import { z } from "zod";
import type { DbTopology } from "./database.js";
import { MONGO_REPLICA_SET, type MaintenanceCommand } from "./database-maintenance.js";

/** A name docker gives a container and its network answers to. */
const CONTAINER_NAME = /^[A-Za-z0-9][A-Za-z0-9._-]{0,62}$/;

/** The longest container name docker (and a DNS label) will take. */
const MAX_NAME = 63;

/** Port every member listens on, whatever its role - see `mongoMemberCommand`. */
export const MONGO_PORT = 27017;
export const MYSQL_PORT = 3306;

/** The config server replica set's name, inside one cluster. */
export const MONGO_CONFIG_SET = "cfg";

/** Members of a config server replica set and of each shard. */
export const MONGO_CLUSTER_SET_SIZE = 3;

/**
 * The environment variable a MongoDB member is handed its key in.
 *
 * The key the members authenticate each other with is generated by Polaris and
 * kept with the instance's other credentials, encrypted. It is a single line of
 * hexadecimal digits - no line break, no control character - so it can travel
 * as an environment value; the member's command writes it to a file owned by
 * the server's user with mode 400, which is what `--keyFile` reads, and unsets
 * the variable before the server starts.
 */
export const MONGO_KEY_ENV = "POLARIS_MONGO_KEY";

/** Where each member's command writes the key. Outside the data volume, so it is
 *  written again from the stored key on every start and never goes stale. */
export const MONGO_CLUSTER_KEYFILE = "/etc/polaris-mongo.key";

/** The account read replicas sign in to their primary with. */
export const MYSQL_REPLICATION_USER = "polaris_replica";

/**
 * Why nothing takes a copy of a sharded cluster yet. A dump through the router
 * while the balancer moves chunks can miss documents or repeat them; the
 * consistent copy the manual describes stops the balancer and dumps every shard
 * and the config servers together, and restoring it is a procedure of its own.
 * Refused, and said on screen, rather than taken inconsistently.
 */
export const SHARDED_DUMP_REFUSAL =
    "Copies of a sharded cluster are not offered yet. A consistent one needs the balancer stopped and every shard and the config servers copied together, and a copy taken through the router while data moves between shards can miss documents or repeat them.";

/** Why a sharded cluster's version is not changed by Polaris yet. */
export const SHARDED_UPGRADE_REFUSAL =
    "Version changes are not offered for a sharded cluster yet: its config servers, shards and router have to move in a set order with the balancer stopped.";

/** What a member of a multi-container instance is there for. */
export type MemberRole = "member" | "config" | "shard" | "router" | "primary" | "replica";

/** One container of an instance laid out over several. */
export interface TopologyMember {
    /** Container name - also the name the others reach it by. */
    readonly name: string;
    readonly role: MemberRole;
    /** The replica set it belongs to (MongoDB). */
    readonly set: string | null;
    /** What its data volume's name ends in, after the instance's own volume
     *  name; null for a member that keeps nothing (the router). The first
     *  member's is empty: it keeps the volume a single instance would have. */
    readonly volumeSuffix: string | null;
}

/** A MongoDB replica set: its name and its members' container names, the
 *  first of which is initiated from and preferred as primary. */
export interface MongoSet {
    readonly name: string;
    readonly hosts: readonly string[];
    /** A config server replica set is initiated with `configsvr: true`. */
    readonly configsvr?: boolean;
}

/**
 * A member's container name: the instance's own with a suffix, cut to fit.
 * What is cut is the middle - the instance's name ends in a hash of its id,
 * and that hash is what keeps two instances' members from sharing a name.
 */
export function memberName(name: string, suffix: string): string {
    if (name.length + suffix.length <= MAX_NAME) return `${name}${suffix}`;
    const cut = name.lastIndexOf("-");
    const tail = cut > 0 ? name.slice(cut) : "";
    return `${name.slice(0, MAX_NAME - suffix.length - tail.length)}${tail}${suffix}`;
}

/**
 * Every container of an instance, the first being the one the instance's own
 * name belongs to - what applications and every maintenance step reach:
 *
 * - a replica set's first member, preferred as its primary;
 * - a sharded cluster's router, which is what clients connect to;
 * - a MySQL primary.
 *
 * A single instance is its one container.
 */
export function topologyMembers(topology: DbTopology, name: string): TopologyMember[] {
    switch (topology.kind) {
        case "replicaSet":
            return Array.from({ length: topology.members }, (_, index) => ({
                name: index === 0 ? name : memberName(name, `-m${index + 1}`),
                role: "member" as const,
                set: MONGO_REPLICA_SET,
                volumeSuffix: index === 0 ? "" : `-m${index + 1}`
            }));
        case "sharded":
            return [
                { name, role: "router", set: null, volumeSuffix: null },
                ...Array.from({ length: MONGO_CLUSTER_SET_SIZE }, (_, index) => ({
                    name: memberName(name, `-cfg${index + 1}`),
                    role: "config" as const,
                    set: MONGO_CONFIG_SET,
                    volumeSuffix: `-cfg${index + 1}`
                })),
                ...Array.from({ length: topology.shards }, (_, shard) =>
                    Array.from({ length: MONGO_CLUSTER_SET_SIZE }, (_, index) => ({
                        name: memberName(name, `-sh${shard + 1}-${index + 1}`),
                        role: "shard" as const,
                        set: shardSetName(shard),
                        volumeSuffix: `-sh${shard + 1}-${index + 1}`
                    }))
                ).flat()
            ];
        case "replicas":
            return [
                { name, role: "primary", set: null, volumeSuffix: "" },
                ...Array.from({ length: topology.replicas }, (_, index) => ({
                    name: memberName(name, `-replica${index + 1}`),
                    role: "replica" as const,
                    set: null,
                    volumeSuffix: `-replica${index + 1}`
                }))
            ];
        default:
            return [{ name, role: "primary", set: null, volumeSuffix: "" }];
    }
}

/** A shard's replica set name, by its position. */
function shardSetName(index: number): string {
    return `shard${index + 1}`;
}

/** The replica sets of a MongoDB layout, config servers first. */
export function mongoSets(topology: DbTopology, name: string): MongoSet[] {
    const members = topologyMembers(topology, name);
    const hostsOf = (set: string) => members.filter((member) => member.set === set).map((member) => member.name);
    if (topology.kind === "replicaSet") return [{ name: MONGO_REPLICA_SET, hosts: hostsOf(MONGO_REPLICA_SET) }];
    if (topology.kind !== "sharded") return [];
    return [
        { name: MONGO_CONFIG_SET, hosts: hostsOf(MONGO_CONFIG_SET), configsvr: true },
        ...Array.from({ length: topology.shards }, (_, index) => ({ name: shardSetName(index), hosts: hostsOf(shardSetName(index)) }))
    ];
}

/** A replica set as a seed list - `rs0/a:27017,b:27017` - the form `sh.addShard`,
 *  `mongos --configdb` and the database tools' `--host` read. */
export function seedList(set: MongoSet): string {
    for (const host of set.hosts) checkHost(host);
    return `${set.name}/${set.hosts.map((host) => `${host}:${MONGO_PORT}`).join(",")}`;
}

function checkHost(host: string): void {
    if (!CONTAINER_NAME.test(host)) throw new Error("A member host is a container name");
}

/** How clients reach a layout: the hosts a connection string lists, the replica
 *  set it names, and - for MySQL with replicas - the name the replicas share. */
export function topologyAddress(
    topology: DbTopology,
    name: string
): { hosts: string[]; replicaSet: string | null; readHost: string | null } {
    if (topology.kind === "replicaSet") {
        return { hosts: topologyMembers(topology, name).map((member) => member.name), replicaSet: MONGO_REPLICA_SET, readHost: null };
    }
    if (topology.kind === "replicas") return { hosts: [name], replicaSet: null, readHost: readHostName(name) };
    // A sharded cluster is reached through its router alone, like one server.
    return { hosts: [name], replicaSet: null, readHost: null };
}

/**
 * The name every read replica answers to beside its own. Docker's resolver
 * answers a name several containers share with all of their addresses, so a
 * client reading from it is spread across the replicas without a balancer.
 */
export function readHostName(name: string): string {
    return memberName(name, "-read");
}

// ---------------------------------------------------------------------------
// MongoDB: starting members
// ---------------------------------------------------------------------------

/**
 * The command a MongoDB member of a replica set or a sharded cluster starts with.
 *
 * It writes the cluster's key from `MONGO_KEY_ENV` to `MONGO_CLUSTER_KEYFILE`,
 * owned by `mongodb` with mode 400 ("the keyfile must not have group or world
 * permissions"), drops the variable, and hands over to the image's entrypoint -
 * which starts the program as the `mongodb` user. `--keyFile` implies `--auth`.
 *
 * - a replica set member: `mongod --replSet rs0 --bind_ip_all`;
 * - a config server: `mongod --configsvr --replSet cfg`, with `--dbpath
 *   /data/db` because the image otherwise gives a config server
 *   `/data/configdb`, which is not where its volume is;
 * - a shard member: `mongod --shardsvr --replSet shardN`;
 * - the router: `mongos --configdb cfg/<config members>`.
 *
 * `--port 27017` is given to config servers and shard members, whose defaults
 * are 27019 and 27018, so every member of every layout is reached on one port.
 *
 * One line, for the reason `mongoReplicaSetCommand` gives.
 */
export function mongoMemberCommand(member: TopologyMember, topology: DbTopology, name: string): string[] {
    let program: string[];
    if (member.role === "router") {
        const config = mongoSets(topology, name).find((set) => set.configsvr);
        if (!config) throw new Error("A router needs a config server replica set");
        program = ["mongos", "--configdb", seedList(config), "--port", String(MONGO_PORT), "--bind_ip_all"];
    } else if (member.role === "config") {
        program = ["mongod", "--configsvr", "--replSet", setOf(member), "--port", String(MONGO_PORT), "--dbpath", "/data/db", "--bind_ip_all"];
    } else if (member.role === "shard") {
        program = ["mongod", "--shardsvr", "--replSet", setOf(member), "--port", String(MONGO_PORT), "--bind_ip_all"];
    } else if (member.role === "member") {
        program = ["mongod", "--replSet", setOf(member), "--bind_ip_all"];
    } else {
        throw new Error(`A ${member.role} is not a MongoDB member`);
    }
    const script = [
        "umask 077",
        `printf '%s' "$${MONGO_KEY_ENV}" > ${MONGO_CLUSTER_KEYFILE}`,
        `chown mongodb:mongodb ${MONGO_CLUSTER_KEYFILE}`,
        `chmod 400 ${MONGO_CLUSTER_KEYFILE}`,
        `unset ${MONGO_KEY_ENV}`,
        `exec docker-entrypoint.sh ${program.join(" ")} --keyFile ${MONGO_CLUSTER_KEYFILE}`
    ].join(" && ");
    return ["sh", "-c", script];
}

function setOf(member: TopologyMember): string {
    if (!member.set || !/^[A-Za-z0-9_-]+$/.test(member.set)) throw new Error("A member belongs to a named replica set");
    return member.set;
}

/**
 * A new cluster key: 384 random bytes as hexadecimal - 768 characters, inside
 * the 6 to 1024 a key may have, and every one of them in the base64 set the
 * manual allows. Generated by the caller from a CSPRNG and passed in here, so
 * this module stays pure; this only checks what it was given is a usable key.
 */
export function isClusterKey(value: unknown): value is string {
    return typeof value === "string" && /^[0-9a-f]{64,1024}$/.test(value);
}

// ---------------------------------------------------------------------------
// MongoDB: joining members
// ---------------------------------------------------------------------------

/** An account to sign in with, or none - the localhost exception, which lets a
 *  member with no users yet be initiated and given its first one. */
export interface MongoAuth {
    readonly username: string;
    readonly password: string;
}

/** `mongosh` against the member it runs in, signed in or not. */
function mongosh(auth: MongoAuth | null, script: string): string[] {
    return [
        "mongosh",
        "--quiet",
        ...(auth ? ["-u", auth.username, "-p", auth.password, "--authenticationDatabase", "admin"] : []),
        "--eval",
        script
    ];
}

/** Whether a member answers at all. `ping` needs no account, so it answers on a
 *  member no user has been created on yet as well as on one that has. */
export function mongoPingCommand(): MaintenanceCommand {
    return { argv: mongosh(null, "db.adminCommand({ ping: 1 }).ok"), describe: "Waiting for the member" };
}

/** Whether an account signs in on a member - false while the member still has
 *  no users, which is when the localhost exception applies instead. */
export function mongoSignInCommand(auth: MongoAuth): MaintenanceCommand {
    return { argv: mongosh(auth, "db.runCommand({ connectionStatus: 1 }).ok"), describe: "Signing in" };
}

/** What a member is in its set right now, as one word on the last line:
 *  `primary`, `secondary` or `other`. `hello` needs no account. */
export function mongoRoleCommand(): MaintenanceCommand {
    return {
        argv: mongosh(null, 'const h = db.hello(); h.isWritablePrimary ? "primary" : h.secondary ? "secondary" : "other"'),
        describe: "Checking the member"
    };
}

/** The word `mongoRoleCommand` printed. */
export function mongoRoleOf(output: string): "primary" | "secondary" | "other" {
    const line = output.trim().split(/\r?\n/).at(-1)?.trim();
    return line === "primary" || line === "secondary" ? line : "other";
}

/**
 * Initiate a replica set with all its members, once, from its first member.
 *
 * The first member is given priority 2 and the others 1, so whenever it is
 * healthy it is the primary: it is the container every maintenance step and
 * every database created inside the instance runs in, and those write.
 *
 * Idempotent, like `mongoInitiateCommand`: a set that is already initiated
 * answers its status instead, and so does one somebody initiated in between.
 * Under the localhost exception `replSetInitiate` and `replSetGetStatus` are
 * both allowed, which is what lets this run before any user exists.
 */
export function mongoSetInitiateCommand(auth: MongoAuth | null, set: MongoSet): MaintenanceCommand {
    for (const host of set.hosts) checkHost(host);
    if (!/^[A-Za-z0-9_-]+$/.test(set.name)) throw new Error("A replica set name is a plain word");
    const members = set.hosts
        .map((host, index) => `{ _id: ${index}, host: ${JSON.stringify(`${host}:${MONGO_PORT}`)}, priority: ${index === 0 ? 2 : 1} }`)
        .join(", ");
    const config = `{ _id: ${JSON.stringify(set.name)}${set.configsvr ? ", configsvr: true" : ""}, members: [${members}] }`;
    const script = `try { rs.status().ok } catch (error) { try { rs.initiate(${config}).ok } catch (again) { if (again.codeName !== "AlreadyInitialized") throw again; 1 } }`;
    return { argv: mongosh(auth, script), describe: `Starting the replica set ${set.name}` };
}

/**
 * Give a member with no users its first one, through the localhost exception:
 * the root account the instance's credentials name. On the router it lands on
 * the config servers and is the cluster's; on a shard it is that shard's own,
 * which the manual asks for so the shard is not left open to anything that can
 * reach its localhost.
 */
export function mongoCreateRootCommand(auth: MongoAuth, where: string): MaintenanceCommand {
    const user = `{ user: ${JSON.stringify(auth.username)}, pwd: ${JSON.stringify(auth.password)}, roles: [{ role: "root", db: "admin" }] }`;
    return {
        argv: mongosh(null, `db.getSiblingDB("admin").createUser(${user}).ok`),
        describe: `Creating the administrative account on ${where}`
    };
}

/**
 * Add every shard the router does not list yet, by its seed list. Asked through
 * `listShards`, whose `host` is `<set>/<members>`, so a shard added on an
 * earlier run - or by a run that stopped half way - is not added twice.
 */
export function mongoAddShardsCommand(auth: MongoAuth, shards: readonly MongoSet[]): MaintenanceCommand {
    const seeds = JSON.stringify(shards.map(seedList));
    const script = [
        'const listed = db.adminCommand({ listShards: 1 }).shards.map((shard) => shard.host.split("/")[0])',
        `for (const seed of ${seeds}) { if (!listed.includes(seed.split("/")[0])) sh.addShard(seed) }`,
        "1"
    ].join("; ");
    return { argv: mongosh(auth, script), describe: "Adding the shards" };
}

/** Ask a primary to step down, so the member it runs in can be restarted
 *  without taking writes down with it. */
export function mongoStepDownCommand(auth: MongoAuth): MaintenanceCommand {
    return { argv: mongosh(auth, "rs.stepDown().ok"), describe: "Handing the primary over" };
}

/** The feature compatibility version a set runs at, as MongoDB prints it: `7.0`. */
export function mongoReadFcvCommand(auth: MongoAuth): MaintenanceCommand {
    return {
        argv: mongosh(auth, "db.adminCommand({ getParameter: 1, featureCompatibilityVersion: 1 }).featureCompatibilityVersion.version"),
        describe: "Reading the feature compatibility version"
    };
}

/** A major version's feature compatibility version: `8` is `8.0`. */
export function fcvOf(version: string): string {
    const major = Number.parseInt(version, 10);
    if (!Number.isInteger(major) || major < 1) throw new Error("A version starts with its major number");
    return `${major}.0`;
}

/**
 * Raise (or settle) the feature compatibility version. From 7.0 the command
 * refuses to run without `confirm: true`; 6.0 does not know the field.
 */
export function mongoSetFcvCommand(auth: MongoAuth, version: string): MaintenanceCommand {
    const fcv = fcvOf(version);
    const confirm = Number.parseInt(fcv, 10) >= 7 ? ", confirm: true" : "";
    return {
        argv: mongosh(auth, `db.adminCommand({ setFeatureCompatibilityVersion: ${JSON.stringify(fcv)}${confirm} }).ok`),
        describe: `Setting the feature compatibility version to ${fcv}`
    };
}

/**
 * The majors a rolling upgrade passes through, in order: every offered version
 * newer than `current` up to `target`. MongoDB moves a replica set one major at
 * a time - 6.0 to 8.0 is 6.0 to 7.0, then 7.0 to 8.0 - and the offered versions
 * are consecutive majors, so these are exactly those steps.
 */
export function rollingPath(offered: readonly string[], current: string, target: string): string[] {
    const major = (value: string) => Number.parseInt(value, 10);
    return [...offered]
        .filter((version) => major(version) > major(current) && major(version) <= major(target))
        .sort((a, b) => major(a) - major(b));
}

/** Each member of a set as `rs.status()` sees it. */
export function mongoSetStatusCommand(auth: MongoAuth | null): MaintenanceCommand {
    return {
        argv: mongosh(auth, "JSON.stringify(rs.status().members.map((m) => ({ name: m.name, state: m.stateStr, health: m.health })))"),
        describe: "Reading the replica set's state"
    };
}

const memberStatusSchema = z.array(
    z.object({ name: z.string().max(300), state: z.string().max(40), health: z.number() })
).max(64);

/** The members `mongoSetStatusCommand` printed, or null for anything else - it
 *  is a container's output, so it is parsed as untrusted. */
export function parseSetStatus(output: string): { name: string; state: string; healthy: boolean }[] | null {
    const line = output.trim().split(/\r?\n/).at(-1) ?? "";
    let raw: unknown;
    try {
        raw = JSON.parse(line);
    } catch {
        return null;
    }
    const parsed = memberStatusSchema.safeParse(raw);
    if (!parsed.success) return null;
    return parsed.data.map((member) => ({
        name: member.name.replace(/:\d+$/, ""),
        state: member.state,
        healthy: member.health === 1
    }));
}

// ---------------------------------------------------------------------------
// MySQL read replicas
// ---------------------------------------------------------------------------

/**
 * The `mysqld` arguments a member of a replicated MySQL starts with: a server id
 * of its own (the primary 1, replicas from 2), and GTIDs on, which the manual
 * requires of source and replica alike. Binary logging is on by default.
 *
 * Replicas are not started with `read_only`: the image's first start runs its
 * setup through a temporary server given these same arguments, and a read-only
 * server refuses that setup. They are made read-only once they follow the
 * primary - see `mysqlFollowCommands`.
 */
export function mysqlMemberCommand(serverId: number): string[] {
    if (!Number.isInteger(serverId) || serverId < 1 || serverId > 4_294_967_295) throw new Error("A server id is a positive integer");
    return ["mysqld", `--server-id=${serverId}`, "--gtid-mode=ON", "--enforce-gtid-consistency=ON"];
}

/** A SQL string literal for a value that has already been checked to hold no
 *  quote or backslash. */
function sqlLiteral(value: string): string {
    if (/['\\]/.test(value)) throw new Error("A value with a quote or a backslash cannot be written into a statement");
    return `'${value}'`;
}

/**
 * The replication account on the primary, created or brought back to the
 * stored password, with the one privilege a replica needs. The statements are
 * written to the primary's binary log, so the replicas get the account too.
 */
export function mysqlReplicationUserCommand(rootPassword: string, replicationPassword: string): MaintenanceCommand {
    const account = `${sqlLiteral(MYSQL_REPLICATION_USER)}@'%'`;
    const secret = sqlLiteral(replicationPassword);
    return {
        argv: [
            "mysql",
            "-uroot",
            `-p${rootPassword}`,
            "-e",
            `CREATE USER IF NOT EXISTS ${account} IDENTIFIED BY ${secret}; ALTER USER ${account} IDENTIFIED BY ${secret}; GRANT REPLICATION SLAVE ON *.* TO ${account};`
        ],
        describe: "Creating the replication account"
    };
}

/**
 * Point a replica at its primary and start it following.
 *
 * `SOURCE_AUTO_POSITION = 1` is GTID replication: the replica asks for every
 * transaction it has not applied, which on a new, empty replica is everything
 * the primary has logged - its database, its accounts and its data. A
 * replication account uses `caching_sha2_password`, which the manual says needs
 * an encrypted connection or the source's public key: `SOURCE_SSL = 1` asks for
 * the first, over the certificate the server generates for itself, and
 * `GET_SOURCE_PUBLIC_KEY = 1` allows the second. `STOP REPLICA` first, because
 * the source can only be changed with both replication threads stopped - which
 * is also what makes this safe to run again.
 *
 * `super_read_only` last, persisted so a restart keeps it: nothing but
 * replication writes to a replica. It implies `read_only`.
 */
export function mysqlFollowCommands(
    rootPassword: string,
    primaryHost: string,
    replicationPassword: string
): MaintenanceCommand[] {
    checkHost(primaryHost);
    const run = (sql: string, describe: string): MaintenanceCommand => ({
        argv: ["mysql", "-uroot", `-p${rootPassword}`, "-e", sql],
        describe
    });
    return [
        run(
            [
                "STOP REPLICA;",
                `CHANGE REPLICATION SOURCE TO SOURCE_HOST = ${sqlLiteral(primaryHost)}, SOURCE_PORT = ${MYSQL_PORT},`,
                `SOURCE_USER = ${sqlLiteral(MYSQL_REPLICATION_USER)}, SOURCE_PASSWORD = ${sqlLiteral(replicationPassword)},`,
                "SOURCE_AUTO_POSITION = 1, SOURCE_SSL = 1, GET_SOURCE_PUBLIC_KEY = 1;",
                "START REPLICA;"
            ].join(" "),
            "Following the primary"
        ),
        run("SET PERSIST super_read_only = ON;", "Making the replica read-only")
    ];
}

/** A replica's replication state, printed vertically. */
export function mysqlReplicaStatusCommand(rootPassword: string): MaintenanceCommand {
    return {
        argv: ["mysql", "-uroot", `-p${rootPassword}`, "-e", "SHOW REPLICA STATUS\\G"],
        describe: "Reading the replica's state"
    };
}

/** What `SHOW REPLICA STATUS\G` said: whether both threads run, how far behind
 *  the replica is, and the last error either thread hit. */
export function parseReplicaStatus(output: string): {
    following: boolean;
    lagSeconds: number | null;
    error: string | null;
} {
    const field = (key: string): string | undefined => {
        const line = output.split(/\r?\n/).find((entry) => entry.trim().startsWith(`${key}:`));
        return line?.slice(line.indexOf(":") + 1).trim();
    };
    const lag = Number.parseInt(field("Seconds_Behind_Source") ?? "", 10);
    const error = field("Last_IO_Error") || field("Last_SQL_Error") || null;
    return {
        following: field("Replica_IO_Running") === "Yes" && field("Replica_SQL_Running") === "Yes",
        lagSeconds: Number.isFinite(lag) ? lag : null,
        error: error ? error.slice(0, 300) : null
    };
}
