/**
 * Validated Polaris environment. Every process boundary that reads configuration
 * goes through here so a misconfigured deployment fails fast and loudly instead
 * of surfacing as a confusing runtime error deep in a request. All keys use the
 * repo-wide POLARIS_ prefix.
 */

import { z } from "zod";
import { randomBytes } from "node:crypto";

/** Accept the usual truthy spellings for boolean flags coming from a shell. */
const boolFromEnv = z
    .string()
    .transform((value) => ["1", "true", "yes", "on"].includes(value.toLowerCase()));

const envSchema = z.object({
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),

    /** Prisma connection string. Postgres in production, SQLite for local/dev. */
    POLARIS_DATABASE_URL: z.string().min(1, "POLARIS_DATABASE_URL is required"),

    /** Which engine POLARIS_DATABASE_URL points at. Drives the auth adapter. */
    POLARIS_DB_PROVIDER: z.enum(["postgresql", "sqlite"]).default("postgresql"),

    /** Public origin the dashboard is served from (used by auth + share links). */
    POLARIS_APP_URL: z.string().url().default("http://localhost:3000"),

    /**
     * Mark session cookies Secure. Off by default so login works over plain HTTP
     * (the polaris.local LAN case). Set true only when the dashboard is served
     * over HTTPS end to end, or the browser will drop the cookie and sign-in will
     * appear to succeed but bounce back to the login page.
     */
    POLARIS_SECURE_COOKIES: boolFromEnv.default("false"),

    /**
     * Local-network hostname advertised over mDNS (like homeassistant.local).
     * Its http(s)://<name>.local and http://<name> origins are trusted by auth so
     * the dashboard is reachable by name on the LAN. Keep in sync with the mdns
     * service's POLARIS_MDNS_HOSTNAME.
     */
    POLARIS_LOCAL_HOSTNAME: z.string().default("polaris"),

    /** better-auth signing secret. Must be set to a long random value in production. */
    POLARIS_AUTH_SECRET: z.string().min(16, "POLARIS_AUTH_SECRET must be at least 16 chars"),

    /**
     * One-time setup token that authorizes creating the first administrator at
     * /setup. Generated by the installer (and printed once), like a claim code.
     * After an admin exists, setup is closed and the token is inert.
     */
    POLARIS_SETUP_TOKEN: z.string().optional(),

    /**
     * Bearer token that authorizes the scheduled-deletion cron endpoint
     * (/api/cron/scheduled-deletions). Optional: when unset the endpoint is
     * disabled and due deletions are only swept lazily as connections are browsed.
     * Set it and have an external scheduler POST with this token for exact timing.
     */
    POLARIS_CRON_SECRET: z.string().optional(),

    /**
     * Base64-encoded 32-byte master key for envelope-encrypting stored storage
     * credentials (AES-256-GCM). Rotating it means bumping the key id; old
     * ciphertexts keep decrypting under their recorded key id.
     */
    POLARIS_MASTER_KEY: z.string().min(1, "POLARIS_MASTER_KEY is required"),

    /**
     * STUN servers a call uses to find a path between two browsers, comma
     * separated (`stun:stun.example.org:3478`).
     *
     * Empty by default, and that is a working default rather than a missing one:
     * two browsers on the same network reach each other on their own addresses,
     * which is the case Polaris is usually in. It is also the private default -
     * with none set, no address of anybody's is offered to a third party.
     *
     * Set it when calls have to cross the internet. Two people behind different
     * NATs frequently still cannot connect with STUN alone, which is what the
     * TURN keys below are for.
     */
    POLARIS_STUN_URLS: z.string().default(""),

    /**
     * A Tenor API key, for the GIF and sticker tabs of the chat picker.
     *
     * Unset means those two tabs say so and offer nothing; emoji still work,
     * because those are a local list. It is deliberately not shipped with a key
     * of Polaris's own: a shared key is a shared quota, and the first busy
     * instance would spend everybody else's.
     */
    POLARIS_TENOR_KEY: z.string().optional(),

    /** A TURN server to relay a call through when the browsers cannot reach each
     *  other directly. Unset means calls work on the local network and between
     *  anybody with a reachable address, and not otherwise. */
    POLARIS_TURN_URL: z.string().optional(),
    POLARIS_TURN_USERNAME: z.string().optional(),
    POLARIS_TURN_PASSWORD: z.string().optional(),

    /**
     * The call server (LiveKit) a deployment was handed, as a WebSocket address
     * and its key pair.
     *
     * Calls can also be pointed at a server from the admin screens, and that is
     * the right shape for somebody running Polaris at home who acquires one
     * later. It is the wrong shape for a deployment: it makes working calls
     * something an administrator has to go and switch on after the fact, in a
     * screen they have no reason to open, and until they do every call between
     * two networks is a pair of people who cannot hear each other.
     *
     * So a deployment can hand them over the way it hands over a database URL,
     * and then nobody configures anything: these win over anything stored, since
     * an operator who put them in the environment of this process meant them.
     */
    POLARIS_CALL_SERVER_URL: z.string().optional(),
    POLARIS_CALL_SERVER_API_KEY: z.string().optional(),
    POLARIS_CALL_SERVER_API_SECRET: z.string().optional(),

    /** Directory for container-local storage and upload scratch space. */
    POLARIS_DATA_DIR: z.string().default("/var/lib/polaris"),

    /** Unix socket the privileged host daemon listens on (full edition only). */
    POLARIS_HOSTD_SOCKET: z.string().default("/run/polaris/hostd.sock"),

    /** File the daemon writes its bearer token to; mounted read-only here. */
    POLARIS_HOSTD_TOKEN_FILE: z.string().default("/run/polaris/hostd.token"),

    /** Optional TCP fallback for platforms without unix-socket sharing. */
    POLARIS_HOSTD_URL: z.string().url().optional(),

    /**
     * CIDRs of reverse proxies whose X-Forwarded-For we trust when resolving a
     * client IP for file-request allowlists and rate limits. Comma-separated.
     * Empty (the safe default) means trust no forwarded header.
     */
    POLARIS_TRUSTED_PROXIES: z
        .string()
        .default("")
        .transform((value) =>
            value
                .split(",")
                .map((entry) => entry.trim())
                .filter((entry) => entry.length > 0)
        ),

    /** Master switch to disable auto-update even in the full edition. */
    POLARIS_AUTO_UPDATE: boolFromEnv.default("true"),

    /** GitHub "owner/repo" the update checker compares the running build against. */
    POLARIS_REPO: z.string().default("FJRG2007/polaris"),

    /** Branch the update checker treats as the release line. */
    POLARIS_UPDATE_BRANCH: z.string().default("main"),

    /**
     * Commit the running image was built from, baked in at build time. Lets the
     * update checker report how many commits behind the latest branch head this
     * deployment is. Empty in dev / source runs, where "up to date" is unknown.
     */
    POLARIS_BUILD_SHA: z.string().default(""),

    /**
     * Registry repository of the dashboard image. The update check reads the
     * commit baked into the published image there, which is what makes "update
     * available" mean "a new image exists to pull" rather than "a commit was
     * pushed" - the two are minutes apart while CI builds.
     */
    POLARIS_WEB_IMAGE: z.string().default("ghcr.io/fjrg2007/polaris-dashboard"),

    /** Tag the deployment runs, mirroring compose. `latest` tracks the release line. */
    POLARIS_IMAGE_TAG: z.string().default("latest"),

    /**
     * Docker-over-SSH access provisioned by `install.sh --ssh`. When enabled, the
     * Containers app can reach the host Engine over a dedicated, forced-command
     * key without mounting the docker socket into the container.
     */
    /** Contact address on the Let's Encrypt account Polaris registers to order the
     *  wildcard certificate. Optional - the account is valid without one, it only
     *  costs the expiry warnings Let's Encrypt would otherwise send. Shared with the
     *  edge, which reads the same value for its per-hostname orders. */
    POLARIS_ACME_EMAIL: z.string().optional(),
    POLARIS_SSH_ENABLED: boolFromEnv.default("false"),
    POLARIS_SSH_HOST: z.string().default("host.docker.internal"),
    POLARIS_SSH_USER: z.string().optional(),
    POLARIS_SSH_PORT: z.coerce.number().int().positive().max(65535).default(22),
    POLARIS_SSH_KEY: z.string().default("/run/polaris-ssh/id_ed25519"),
    POLARIS_SSH_KNOWN_HOSTS: z.string().default("/run/polaris-ssh/known_hosts")
});

export type PolarisEnv = z.infer<typeof envSchema>;

let cached: PolarisEnv | undefined;

/**
 * Inert placeholders used only while `next build` collects page data. The route
 * modules are imported at build time, which constructs auth/db before any real
 * environment exists; without these the build would fail on missing secrets even
 * though nothing is actually served. Runtime never sees these - NEXT_PHASE is
 * unset then, so validation stays strict.
 *
 * The two secrets are drawn fresh per build rather than being fixed strings: a
 * throwaway key nothing signs with should still be a real key, and a short,
 * guessable one makes better-auth warn on every page it prerenders.
 */
const BUILD_PLACEHOLDERS: Record<string, string> = {
    POLARIS_DATABASE_URL: "postgresql://build:build@localhost:5432/build",
    POLARIS_AUTH_SECRET: randomBytes(32).toString("base64"),
    POLARIS_MASTER_KEY: randomBytes(32).toString("base64")
};

/**
 * Parse and cache process.env once. Throws a readable aggregated error listing
 * every invalid or missing key so an operator can fix them all in one pass.
 */
export function loadEnv(source: NodeJS.ProcessEnv = process.env): PolarisEnv {
    if (cached) return cached;
    const isBuild = source.NEXT_PHASE === "phase-production-build";
    const effective = isBuild ? { ...BUILD_PLACEHOLDERS, ...source } : source;
    const parsed = envSchema.safeParse(effective);
    if (!parsed.success) {
        const issues = parsed.error.issues
            .map((issue) => `  - ${issue.path.join(".")}: ${issue.message}`)
            .join("\n");
        throw new Error(`Invalid Polaris environment:\n${issues}`);
    }
    cached = parsed.data;
    return cached;
}

/** Reset the cache. Test-only; production loads env exactly once. */
export function resetEnvCache(): void {
    cached = undefined;
}
