/**
 * One-command local launch, no containers. Uses SQLite so there is nothing to
 * install: generates a SQLite schema, pushes it, writes a dev env with stable
 * secrets (kept across restarts so encrypted data stays decryptable), and starts
 * the Next dev server. For the production, multi-user stack use docker/ instead.
 *
 *   npm run dev:up
 */

import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";
import { spawn, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const webDir = join(root, "apps", "web");
const dbDir = join(root, "packages", "db");
const prismaDir = join(dbDir, "prisma");
const sqliteSchema = join(prismaDir, "schema.sqlite.prisma");
const envFile = join(webDir, ".env.local");

const toUrlPath = (p) => p.replace(/\\/g, "/");

function log(message) {
    process.stdout.write(`[dev-up] ${message}\n`);
}

/** Create or reuse the dev env. Secrets are generated once and then reused. */
function ensureEnv() {
    if (existsSync(envFile)) {
        log("Reusing existing apps/web/.env.local");
        return Object.fromEntries(
            readFileSync(envFile, "utf8")
                .split("\n")
                .filter((line) => line.includes("=") && !line.trimStart().startsWith("#"))
                .map((line) => {
                    const index = line.indexOf("=");
                    return [line.slice(0, index).trim(), line.slice(index + 1).trim()];
                })
        );
    }
    const dataDir = join(root, ".dev-data");
    mkdirSync(dataDir, { recursive: true });
    const values = {
        NODE_ENV: "development",
        POLARIS_DB_PROVIDER: "sqlite",
        POLARIS_DATABASE_URL: `file:${toUrlPath(join(prismaDir, "polaris-dev.db"))}`,
        POLARIS_AUTH_SECRET: randomBytes(24).toString("hex"),
        POLARIS_MASTER_KEY: randomBytes(32).toString("base64"),
        POLARIS_SETUP_TOKEN: randomBytes(18).toString("hex"),
        POLARIS_APP_URL: "http://localhost:3000",
        POLARIS_DATA_DIR: toUrlPath(dataDir)
    };
    const body =
        "# Local dev (SQLite, no containers). Generated by scripts/dev-up.mjs.\n" +
        Object.entries(values)
            .map(([key, value]) => `${key}=${value}`)
            .join("\n") +
        "\n";
    writeFileSync(envFile, body);
    log("Wrote apps/web/.env.local with fresh secrets");
    return values;
}

/**
 * The script a workspace command runs, resolved from the package that depends on
 * it and started with THIS node.
 *
 * Not `npx`: npx looks in the current directory's node_modules and, finding
 * nothing, tries to FETCH the package from the registry - which asks a question
 * nobody is there to answer and exits 1, reporting only "npx.cmd prisma generate
 * ... exited with 1". That is what happens whenever the install left the binary
 * somewhere other than the workspace root: an installer other than npm, a partial
 * install, or no install at all. Resolving it here works for any of those layouts
 * and says what to do when the package genuinely is not installed.
 */
function commandScript(pkg, fromDir) {
    const resolve = createRequire(join(fromDir, "package.json")).resolve;
    let manifestPath;
    try {
        manifestPath = resolve(`${pkg}/package.json`);
    } catch {
        throw new Error(
            `${pkg} is not installed. Run "npm install" in ${root} first (this is an npm-workspaces monorepo).`
        );
    }
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    const bin = typeof manifest.bin === "string" ? manifest.bin : manifest.bin?.[pkg];
    if (!bin) throw new Error(`${pkg} exposes no "${pkg}" command`);
    return join(dirname(manifestPath), bin);
}

function run(command, args, env) {
    const result = spawnSync(command, args, { cwd: root, env, stdio: "inherit" });
    if (result.status !== 0) {
        throw new Error(`${command} ${args.join(" ")} exited with ${result.status}`);
    }
}

const env = { ...process.env, ...ensureEnv() };

log("Generating SQLite schema");
run(process.execPath, [join(root, "scripts", "gen-sqlite-schema.mjs")], env);

log("Generating Prisma client and pushing the schema");
const prisma = commandScript("prisma", dbDir);
run(process.execPath, [prisma, "generate", `--schema=${sqliteSchema}`], env);
run(process.execPath, [prisma, "db", "push", `--schema=${sqliteSchema}`, "--skip-generate", "--accept-data-loss"], env);

log(`First run? Open http://localhost:3000/oauth/setup?token=${env.POLARIS_SETUP_TOKEN}`);
log("Starting the dashboard at http://localhost:3000 (Ctrl+C to stop)");
const dev = spawn(process.execPath, [commandScript("next", webDir), "dev"], { cwd: webDir, env, stdio: "inherit" });
dev.on("exit", (code) => process.exit(code ?? 0));
