/**
 * One-command local launch, no containers. Uses SQLite so there is nothing to
 * install: generates a SQLite schema, pushes it, writes a dev env with stable
 * secrets (kept across restarts so encrypted data stays decryptable), and starts
 * the Next dev server. For the production, multi-user stack use docker/ instead.
 *
 *   npm run dev:up
 */

import { spawn, spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const webDir = join(root, "apps", "web");
const prismaDir = join(root, "packages", "db", "prisma");
const sqliteSchema = join(prismaDir, "schema.sqlite.prisma");
const envFile = join(webDir, ".env.local");
const isWindows = process.platform === "win32";
const npx = isWindows ? "npx.cmd" : "npx";

const toUrlPath = (p) => p.replace(/\\/g, "/");

function log(message) {
    process.stdout.write(`[dev-up] ${message}\n`);
}

/** Create or reuse the dev env. Secrets are generated once and then reused. */
function ensureEnv() {
    if (existsSync(envFile)) {
        log("Reusing existing apps/web/.env.local");
        return Object.fromEntries(
            readFileSync(envFile, "utf8")
                .split("\n")
                .filter((line) => line.includes("=") && !line.trimStart().startsWith("#"))
                .map((line) => {
                    const index = line.indexOf("=");
                    return [line.slice(0, index).trim(), line.slice(index + 1).trim()];
                })
        );
    }
    const dataDir = join(root, ".dev-data");
    mkdirSync(dataDir, { recursive: true });
    const values = {
        NODE_ENV: "development",
        POLARIS_DB_PROVIDER: "sqlite",
        POLARIS_DATABASE_URL: `file:${toUrlPath(join(prismaDir, "polaris-dev.db"))}`,
        POLARIS_AUTH_SECRET: randomBytes(24).toString("hex"),
        POLARIS_MASTER_KEY: randomBytes(32).toString("base64"),
        POLARIS_SETUP_TOKEN: randomBytes(18).toString("hex"),
        POLARIS_APP_URL: "http://localhost:3000",
        POLARIS_DATA_DIR: toUrlPath(dataDir)
    };
    const body =
        "# Local dev (SQLite, no containers). Generated by scripts/dev-up.mjs.\n" +
        Object.entries(values)
            .map(([key, value]) => `${key}=${value}`)
            .join("\n") +
        "\n";
    writeFileSync(envFile, body);
    log("Wrote apps/web/.env.local with fresh secrets");
    return values;
}

function run(command, args, env) {
    const result = spawnSync(command, args, { cwd: root, env, stdio: "inherit", shell: isWindows });
    if (result.status !== 0) {
        throw new Error(`${command} ${args.join(" ")} exited with ${result.status}`);
    }
}

const env = { ...process.env, ...ensureEnv() };

log("Generating SQLite schema");
run(process.execPath, [join(root, "scripts", "gen-sqlite-schema.mjs")], env);

log("Generating Prisma client and pushing the schema");
run(npx, ["prisma", "generate", `--schema=${sqliteSchema}`], env);
run(npx, ["prisma", "db", "push", `--schema=${sqliteSchema}`, "--skip-generate", "--accept-data-loss"], env);

log(`First run? Open http://localhost:3000/oauth/setup?token=${env.POLARIS_SETUP_TOKEN}`);
log("Starting the dashboard at http://localhost:3000 (Ctrl+C to stop)");
const dev = spawn(npx, ["next", "dev"], { cwd: webDir, env, stdio: "inherit", shell: isWindows });
dev.on("exit", (code) => process.exit(code ?? 0));
