/**
 * Knowing when a download has actually started.
 *
 * A download is a navigation, not a fetch: the browser takes the URL, asks for
 * it, and saves what comes back, and the page that started it is told nothing.
 * That is fine when the answer is immediate and wrong when it is not - a file on
 * a NAS behind a fresh SSH handshake, or a folder the server has to build into a
 * zip first, can be twenty seconds of a button that looks like it did nothing.
 * People press it again. Then again.
 *
 * So the request carries a ticket and the response sets a cookie naming it. The
 * cookie can only be set when the server has answered, which is exactly the
 * moment the browser starts saving the file - so a page watching for it knows
 * when to stop saying "preparing" without ever seeing the bytes.
 *
 * The ticket is generated by the browser and lands in a `Set-Cookie` header, so
 * it is checked rather than trusted on the way through: anything but a short
 * run of letters and digits is refused, and no header is set at all.
 */

/** What the cookie is called, before the ticket. */
const PREFIX = "polaris-dl-";

/** Tickets are made here and read back here; the only thing crossing the wire is
 *  the name. Letters and digits, so nothing in it can end a header. */
const SHAPE = /^[a-z0-9]{8,32}$/;

/** A ticket for one download. Random rather than sequential so two tabs of the
 *  same browser cannot answer each other's. */
export function newDownloadTicket(): string {
    const bytes = new Uint8Array(12);
    crypto.getRandomValues(bytes);
    return [...bytes].map((byte) => byte.toString(36).padStart(2, "0")).join("").slice(0, 24);
}

/** Whether a ticket off a request is one this will act on. */
export function validDownloadTicket(ticket: string | null): ticket is string {
    return ticket !== null && SHAPE.test(ticket);
}

/**
 * The header that tells the page its download has begun.
 *
 * Short-lived and path-wide: it exists for the seconds between the browser
 * asking and the page noticing, and the page deletes it as soon as it has. Not
 * `HttpOnly`, because being read by the page is the entire purpose. It carries
 * nothing - the value is a constant - so there is nothing in it to leak.
 */
export function downloadTicketCookie(ticket: string): string {
    return `${PREFIX}${ticket}=1; Path=/; Max-Age=120; SameSite=Lax`;
}

/** Whether the browser has been handed the cookie for this ticket yet. */
export function downloadStarted(ticket: string): boolean {
    return document.cookie.split("; ").some((entry) => entry.startsWith(`${PREFIX}${ticket}=`));
}

/** Take it back off once it has been noticed, so a browser does not accumulate
 *  one per file anybody ever downloaded. */
export function forgetDownloadTicket(ticket: string): void {
    document.cookie = `${PREFIX}${ticket}=; Path=/; Max-Age=0; SameSite=Lax`;
}
