/**
 * The requests Polaris sends to the mail server it runs, as pure values.
 *
 * The engine is Stalwart (v0.16). From that version every administrative action
 * is a JMAP object behind the same `/jmap` endpoint that serves mail: a domain is
 * `x:Domain`, a mailbox is an `x:Account` of type `User`, a forward is an
 * `x:MailingList`, the outbound relay is an `x:MtaRoute`, and so on, each with the
 * standard `/get`, `/set` and `/query` methods under the `urn:stalwart:jmap`
 * capability. Everything here is built from the engine's own schema reference
 * (stalw.art/docs/ref/object) - no field is guessed.
 *
 * Three encodings in that schema differ from plain JSON and are the whole reason
 * these builders exist rather than object literals at the call site:
 *
 * - a list is an object keyed by stringified positions (`{"0": ..., "1": ...}`),
 * - a set is an object mapping each member to `true`,
 * - a variant is an object with an `@type` naming it.
 *
 * Kept pure so the exact bytes that reach the engine are asserted in a test.
 */

/** The capabilities every management request declares. */
export const STALWART_JMAP_USING = ["urn:ietf:params:jmap:core", "urn:stalwart:jmap"] as const;

/** One JMAP method call: its name, its arguments, and the id its answer comes
 *  back under. */
export type JmapCall = readonly [string, Record<string, unknown>, string];

/** A whole request. */
export interface JmapRequest {
    readonly using: readonly string[];
    readonly methodCalls: readonly JmapCall[];
}

export function jmapRequest(calls: readonly JmapCall[]): JmapRequest {
    return { using: [...STALWART_JMAP_USING], methodCalls: calls };
}

/** The engine's list encoding: positions as string keys. */
export function listOf<T>(items: readonly T[]): Record<string, T> {
    const out: Record<string, T> = {};
    items.forEach((item, index) => {
        out[String(index)] = item;
    });
    return out;
}

/** The engine's set encoding: every member mapped to `true`. */
export function setOf(values: readonly string[]): Record<string, true> {
    const out: Record<string, true> = {};
    for (const value of values) out[value] = true;
    return out;
}

/** Read a list the engine sent back, in position order, whichever encoding it
 *  arrived in. */
export function fromList<T>(value: unknown): T[] {
    if (Array.isArray(value)) return value as T[];
    if (!value || typeof value !== "object") return [];
    return Object.entries(value as Record<string, T>)
        .sort(([left], [right]) => Number(left) - Number(right))
        .map(([, item]) => item);
}

/** Read a set the engine sent back as its members. */
export function fromSet(value: unknown): string[] {
    if (Array.isArray(value)) return value.filter((item): item is string => typeof item === "string");
    if (!value || typeof value !== "object") return [];
    return Object.entries(value as Record<string, unknown>)
        .filter(([, member]) => member === true)
        .map(([key]) => key);
}

// ---------------------------------------------------------------------------
// First start
// ---------------------------------------------------------------------------

/**
 * Leave bootstrap mode: name the server and its first domain.
 *
 * A fresh engine starts in bootstrap mode, serving only the management API and
 * the `Bootstrap` singleton. Setting it writes the configuration, provisions
 * the rest and restarts into normal service. The certificate is requested from
 * Let's Encrypt and the first domain's DKIM keys are generated by the engine
 * itself, which is what makes its published key and its signing key the same.
 */
export function bootstrapCall(input: { hostname: string; domain: string }): JmapCall {
    return [
        "x:Bootstrap/set",
        {
            update: {
                singleton: {
                    serverHostname: input.hostname,
                    defaultDomain: input.domain,
                    requestTlsCertificate: true,
                    generateDkimKeys: true
                }
            }
        },
        "bootstrap"
    ];
}

// ---------------------------------------------------------------------------
// Domains
// ---------------------------------------------------------------------------

/**
 * Create a domain. DKIM keys are the engine's to generate and rotate; DNS stays
 * manual on its side because Polaris is the one that publishes the records -
 * through the operator's own DNS integration, with a plan they can read first.
 */
export function domainCreateCall(name: string): JmapCall {
    return [
        "x:Domain/set",
        {
            create: {
                domain: {
                    name,
                    aliases: {},
                    certificateManagement: { "@type": "Manual" },
                    dkimManagement: { "@type": "Automatic" },
                    dnsManagement: { "@type": "Manual" },
                    subAddressing: { "@type": "Enabled" }
                }
            }
        },
        "domain"
    ];
}

/** Every domain, with what the screens show and the zone the engine expects. */
export function domainListCalls(): JmapCall[] {
    return [
        ["x:Domain/query", {}, "q"],
        [
            "x:Domain/get",
            {
                "#ids": { resultOf: "q", name: "x:Domain/query", path: "/ids" },
                properties: ["id", "name", "isEnabled", "catchAllAddress", "dnsZoneFile", "reportAddressUri"]
            },
            "domains"
        ]
    ];
}

/** Route mail for unknown addresses at a domain to one address, or stop. */
export function domainCatchAllCall(domainId: string, address: string | null): JmapCall {
    return ["x:Domain/set", { update: { [domainId]: { catchAllAddress: address } } }, "catchall"];
}

export function domainDestroyCall(domainId: string): JmapCall {
    return ["x:Domain/set", { destroy: [domainId] }, "destroy"];
}

/**
 * Where a domain's DMARC, TLS-RPT and CAA reports are sent. The engine writes
 * this address into the `rua` of the DMARC and TLS-RPT records it generates, so
 * it has to be an address at the same domain: a report address at another
 * domain is only honoured by receivers when that domain publishes an
 * authorization record for it (RFC 7489 section 7.1).
 */
export function domainReportAddressCall(domainId: string, address: string): JmapCall {
    return ["x:Domain/set", { update: { [domainId]: { reportAddressUri: `mailto:${address}` } } }, "reports"];
}

// ---------------------------------------------------------------------------
// Mailboxes and aliases
// ---------------------------------------------------------------------------

/** One password credential, in the engine's credential variant. */
function passwordCredential(secret: string): Record<string, unknown> {
    return { "@type": "Password", secret };
}

export interface MailboxCreate {
    readonly name: string;
    readonly domainId: string;
    readonly password: string;
    /** Bytes; null leaves the account without a disk quota. */
    readonly quotaBytes: number | null;
    /** An administrator of the mail server itself - only ever the account
     *  Polaris manages it with. */
    readonly admin?: boolean;
    readonly description?: string;
}

/** Create a mailbox: a `User` account with one password. */
export function accountCreateCall(input: MailboxCreate): JmapCall {
    return [
        "x:Account/set",
        {
            create: {
                account: {
                    "@type": "User",
                    name: input.name,
                    domainId: input.domainId,
                    aliases: {},
                    credentials: listOf([passwordCredential(input.password)]),
                    encryptionAtRest: { "@type": "Disabled" },
                    memberGroupIds: {},
                    permissions: { "@type": "Inherit" },
                    quotas: input.quotaBytes !== null ? { maxDiskQuota: input.quotaBytes } : {},
                    roles: { "@type": input.admin ? "Admin" : "User" },
                    ...(input.description ? { description: input.description } : {})
                }
            }
        },
        "account"
    ];
}

export function accountListCalls(): JmapCall[] {
    return [
        ["x:Account/query", {}, "q"],
        [
            "x:Account/get",
            {
                "#ids": { resultOf: "q", name: "x:Account/query", path: "/ids" },
                properties: ["id", "name", "domainId", "emailAddress", "aliases", "quotas", "description", "roles"]
            },
            "accounts"
        ]
    ];
}

/** Replace a mailbox's password. The list is replaced whole, which is the point:
 *  the old password stops working the moment this lands. */
export function accountPasswordCall(accountId: string, password: string): JmapCall {
    return [
        "x:Account/set",
        { update: { [accountId]: { credentials: listOf([passwordCredential(password)]) } } },
        "password"
    ];
}

export function accountQuotaCall(accountId: string, quotaBytes: number | null): JmapCall {
    return [
        "x:Account/set",
        { update: { [accountId]: { quotas: quotaBytes !== null ? { maxDiskQuota: quotaBytes } : {} } } },
        "quota"
    ];
}

/** Replace a mailbox's aliases with this list. */
export function accountAliasesCall(
    accountId: string,
    aliases: readonly { name: string; domainId: string }[]
): JmapCall {
    return [
        "x:Account/set",
        {
            update: {
                [accountId]: {
                    aliases: listOf(aliases.map((alias) => ({ enabled: true, name: alias.name, domainId: alias.domainId })))
                }
            }
        },
        "aliases"
    ];
}

export function accountDestroyCall(accountId: string): JmapCall {
    return ["x:Account/set", { destroy: [accountId] }, "destroy"];
}

// ---------------------------------------------------------------------------
// Forwards
// ---------------------------------------------------------------------------

/**
 * A forward: an address at one of the server's domains whose mail goes on to
 * one or more other addresses. The engine's own shape for that is a mailing
 * list, which is exactly what a forward to several people is.
 */
export function forwardCreateCall(input: {
    name: string;
    domainId: string;
    recipients: readonly string[];
    description?: string;
}): JmapCall {
    return [
        "x:MailingList/set",
        {
            create: {
                forward: {
                    name: input.name,
                    domainId: input.domainId,
                    aliases: {},
                    recipients: setOf(input.recipients),
                    ...(input.description ? { description: input.description } : {})
                }
            }
        },
        "forward"
    ];
}

export function forwardListCalls(): JmapCall[] {
    return [
        ["x:MailingList/query", {}, "q"],
        [
            "x:MailingList/get",
            {
                "#ids": { resultOf: "q", name: "x:MailingList/query", path: "/ids" },
                properties: ["id", "name", "domainId", "emailAddress", "recipients", "description"]
            },
            "forwards"
        ]
    ];
}

export function forwardDestroyCall(forwardId: string): JmapCall {
    return ["x:MailingList/set", { destroy: [forwardId] }, "destroy"];
}

// ---------------------------------------------------------------------------
// Sending through somebody else
// ---------------------------------------------------------------------------

/** What the relay route is called, so it can be found and replaced. */
export const RELAY_ROUTE_NAME = "polaris-relay";

/** The route the engine delivers through when no relay is set: straight to the
 *  recipient's MX. */
export const DIRECT_ROUTE_NAME = "mx";

export interface RelayRoute {
    readonly host: string;
    readonly port: number;
    /** TLS from the first byte (465) rather than STARTTLS. */
    readonly implicitTls: boolean;
    readonly username: string;
    readonly secret: string;
}

/** Create the relay route every outbound message is sent through. */
export function relayRouteCreateCall(relay: RelayRoute): JmapCall {
    return [
        "x:MtaRoute/set",
        {
            create: {
                relay: {
                    "@type": "Relay",
                    name: RELAY_ROUTE_NAME,
                    address: relay.host,
                    port: relay.port,
                    protocol: "smtp",
                    implicitTls: relay.implicitTls,
                    allowInvalidCerts: false,
                    authUsername: relay.username,
                    authSecret: relay.secret ? { "@type": "Value", secret: relay.secret } : { "@type": "None" }
                }
            }
        },
        "route"
    ];
}

export function routeListCall(): JmapCall[] {
    return [
        ["x:MtaRoute/query", {}, "q"],
        [
            "x:MtaRoute/get",
            { "#ids": { resultOf: "q", name: "x:MtaRoute/query", path: "/ids" }, properties: ["id", "name"] },
            "routes"
        ]
    ];
}

export function routeDestroyCall(routeId: string): JmapCall {
    return ["x:MtaRoute/set", { destroy: [routeId] }, "destroy"];
}

/**
 * Choose the route every queued message leaves by. The strategy's `route` is an
 * expression; with no conditions it is its `else`, a quoted route name.
 */
export function outboundRouteCall(routeName: string): JmapCall {
    if (!/^[a-z0-9-]+$/.test(routeName)) throw new Error("not a route name");
    return [
        "x:MtaOutboundStrategy/set",
        { update: { singleton: { route: { else: `'${routeName}'` } } } },
        "strategy"
    ];
}

// ---------------------------------------------------------------------------
// Reading a mailbox (RFC 8621)
// ---------------------------------------------------------------------------

/** The capabilities a request about somebody's mail declares. */
export const JMAP_MAIL_USING = ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"] as const;

export function jmapMailRequest(calls: readonly JmapCall[]): JmapRequest {
    return { using: [...JMAP_MAIL_USING], methodCalls: calls };
}

/**
 * The oldest messages not read yet, with their attachments. Read in batches and
 * marked seen as they are handled, so a mailbox that has collected a year of
 * reports is worked through over several runs rather than in one.
 */
export function unreadWithAttachmentsCalls(accountId: string, limit: number): JmapCall[] {
    return [
        [
            "Email/query",
            {
                accountId,
                filter: { notKeyword: "$seen" },
                sort: [{ property: "receivedAt", isAscending: true }],
                limit
            },
            "q"
        ],
        [
            "Email/get",
            {
                accountId,
                "#ids": { resultOf: "q", name: "Email/query", path: "/ids" },
                properties: ["id", "receivedAt", "attachments"]
            },
            "messages"
        ]
    ];
}

export function markSeenCall(accountId: string, emailIds: readonly string[]): JmapCall {
    const update: Record<string, Record<string, boolean>> = {};
    for (const id of emailIds) update[id] = { "keywords/$seen": true };
    return ["Email/set", { accountId, update }, "seen"];
}

/**
 * A blob's download path, from the session's `downloadUrl` template (RFC 8620
 * section 2): `{accountId}`, `{blobId}`, `{type}` and `{name}`, each
 * percent-encoded. Only the path and query are kept; the host in the template
 * is the public name, and the request goes over the management endpoint.
 */
export function downloadPath(
    template: string,
    values: { accountId: string; blobId: string; type: string; name: string }
): string {
    const expanded = template.replace(/\{(accountId|blobId|type|name)\}/g, (_, key: keyof typeof values) =>
        encodeURIComponent(values[key])
    );
    const url = new URL(expanded, "http://engine");
    return `${url.pathname}${url.search}`;
}

// ---------------------------------------------------------------------------
// Hearing about incoming mail
// ---------------------------------------------------------------------------

/** The events a webhook asks for: every message the server takes in, and which
 *  of the two its spam filter decided it was. */
export const INBOUND_EVENTS = ["message-ingest.ham", "message-ingest.spam"] as const;

/** Tell the engine to post incoming-mail events to Polaris, signed. */
export function webhookCreateCall(url: string, signingSecret: string): JmapCall {
    return [
        "x:WebHook/set",
        {
            create: {
                hook: {
                    url,
                    events: setOf(INBOUND_EVENTS),
                    eventsPolicy: "include",
                    signatureKey: { "@type": "Value", secret: signingSecret },
                    httpAuth: { "@type": "Unauthenticated" }
                }
            }
        },
        "webhook"
    ];
}

// ---------------------------------------------------------------------------
// Answers
// ---------------------------------------------------------------------------

/** Something the engine refused, in its own words. */
export class StalwartRefusal extends Error {
    public constructor(
        message: string,
        public readonly type: string
    ) {
        super(message);
        this.name = "StalwartRefusal";
    }
}

/** The arguments of the answer to one call, or the engine's refusal of it. */
export function answerOf(response: unknown, callId: string): Record<string, unknown> {
    const responses =
        response && typeof response === "object" && Array.isArray((response as { methodResponses?: unknown }).methodResponses)
            ? ((response as { methodResponses: unknown[] }).methodResponses as unknown[])
            : [];
    for (const entry of responses) {
        if (!Array.isArray(entry) || entry[2] !== callId) continue;
        const [name, args] = entry as [string, Record<string, unknown>];
        if (name === "error") {
            const type = typeof args?.type === "string" ? args.type : "error";
            const description = typeof args?.description === "string" ? args.description : type;
            throw new StalwartRefusal(description, type);
        }
        return args ?? {};
    }
    throw new StalwartRefusal("The mail server did not answer that request", "missing");
}

/** The id the engine gave something just created, or its reason for refusing. */
export function createdId(response: unknown, callId: string, key: string): string {
    const answer = answerOf(response, callId);
    const created = (answer.created as Record<string, { id?: unknown }> | undefined)?.[key];
    if (created && typeof created.id === "string") return created.id;
    throw setRefusal((answer.notCreated as Record<string, unknown> | undefined)?.[key], "create");
}

/** Throw the reason an update or a destroy was refused, if it was. */
export function assertApplied(response: unknown, callId: string, id: string): void {
    const answer = answerOf(response, callId);
    const refused =
        (answer.notUpdated as Record<string, unknown> | undefined)?.[id] ??
        (answer.notDestroyed as Record<string, unknown> | undefined)?.[id];
    if (refused) throw setRefusal(refused, "update");
}

function setRefusal(error: unknown, verb: string): StalwartRefusal {
    const shape = (error ?? {}) as { type?: unknown; description?: unknown; properties?: unknown };
    const type = typeof shape.type === "string" ? shape.type : "invalidProperties";
    const properties = Array.isArray(shape.properties) ? ` (${shape.properties.join(", ")})` : "";
    const description =
        typeof shape.description === "string" && shape.description
            ? shape.description
            : `The mail server would not ${verb} that`;
    return new StalwartRefusal(`${description}${properties}`, type);
}

/** The objects a `/get` answered with. */
export function listOfAnswer<T>(response: unknown, callId: string): T[] {
    const answer = answerOf(response, callId);
    return Array.isArray(answer.list) ? (answer.list as T[]) : [];
}
